name: GridX Matching Engine Build Pipeline

on:
  push:
    branches: [ main ] 
     

  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Python (required by Conan)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Cache Conan packages
      - name: Cache Conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: conan-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('conanfile.py') }}
          restore-keys: |
            conan-${{ runner.os }}-${{ runner.arch }}-
            conan-${{ runner.os }}-

      # Install build tools : for now we comment this out as we are using the pre-installed versions on the GitHub runner. Uncomment if you need to install specific versions.
      # - name: Install build dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       clang \
      #       cmake \
      #       clang-tools \
      #       ninja-build

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install llvm
          echo "$(brew --prefix llvm)/bin" >> "$GITHUB_PATH"

      # Install Conan
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      # Detect compiler
      - name: Detect Conan profile
        run: |
          conan profile detect --force

      # Install dependencies
      - name: Install Conan dependencies
        run: |
          conan install . \
            --settings build_type=Release \
            --build=missing

      # Configure
      - name: Configure CMake
        run: |
              cmake --preset release 

      # Build
      - name: Build project
        run: |
          cmake --build build/release

      # Run unit tests
      # - name: Run unit tests
      #   run: |
      #     ctest \
      #       --test-dir build/release \
      #       --output-on-failure

      

      # Static analysis
      - name: Run clang-tidy
        run: |
          run-clang-tidy -p build/release